FROM elasticsearch:2.4.1

RUN /usr/share/elasticsearch/bin/plugin install license
RUN /usr/share/elasticsearch/bin/plugin install marvel-agent
RUN /usr/share/elasticsearch/bin/plugin install analysis-kuromoji
